# Generated by Django 3.0.8 on 2021-08-15 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_auto_20210815_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acc.Customer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acc.Products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='servicename',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acc.Services'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acc.Products'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acc.Vendor'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
